CREATE TABLE IF NOT EXISTS category (
  name         VARCHAR(64)  PRIMARY KEY,
  display_name VARCHAR(128) NOT NULL,
  sort_order   SMALLINT     NOT NULL
);

-- default_category is nullable because a bank does not determine what a transaction was for:
-- FNB resolves a merchant name and then falls through the ladder.
CREATE TABLE IF NOT EXISTS merchant (
  name             VARCHAR(120) PRIMARY KEY,
  default_category VARCHAR(64)  NULL REFERENCES category(name)
);

CREATE TABLE IF NOT EXISTS merchant_pattern (
  pattern       VARCHAR(120) PRIMARY KEY,
  merchant_name VARCHAR(120) NOT NULL REFERENCES merchant(name)
);

CREATE INDEX IF NOT EXISTS idx_merchant_pattern_merchant_name ON merchant_pattern(merchant_name);

INSERT INTO category (name, display_name, sort_order) VALUES
  ('Groceries', 'Groceries & Supermarkets', 0),
  ('Dining Out', 'Restaurants & Cafes', 1),
  ('Entertainment', 'Entertainment & Leisure', 2),
  ('Transport', 'Transport & Travel', 3),
  ('Utilities', 'Utilities', 4),
  ('Health', 'Health & Wellness', 5),
  ('Education', 'Education', 6),
  ('Shopping', 'Shopping', 7),
  ('Subscriptions', 'Subscriptions & Memberships', 8),
  ('Savings', 'Savings & Investments', 9),
  ('Income', 'Income', 10),
  ('Fees', 'Fees & Charges', 11),
  ('Insurance', 'Insurance', 12),
  ('Miscellaneous', 'Miscellaneous', 13)
ON CONFLICT (name) DO NOTHING;

-- Sandton City Parking previously mapped to "Parking", which is not a category; seeded NULL
-- rather than inventing a value. Standard Bank is NULL for the same reason FNB is: a bank does
-- not determine what a transaction was for, and mapping it to Income put negative bank fees in
-- the Income summary.
INSERT INTO merchant (name, default_category) VALUES
  ('Checkers', 'Groceries'),
  ('Uber Eats', 'Dining Out'),
  ('Uber', 'Transport'),
  ('Apple', 'Subscriptions'),
  ('Capitec', 'Utilities'),
  ('Allan Gray', 'Savings'),
  ('Takealot', 'Shopping'),
  ('Clicks', 'Health'),
  ('Dischem', 'Health'),
  ('FNB', NULL),
  ('Spotify', 'Subscriptions'),
  ('McDonalds', 'Dining Out'),
  ('Nandos', 'Dining Out'),
  ('Woolworths', 'Groceries'),
  ('Engen', 'Transport'),
  ('Kumar Kailey', 'Shopping'),
  ('Virgin Active', 'Health'),
  ('Steam Games', 'Entertainment'),
  ('Quicket', 'Entertainment'),
  ('Naked Insurance', 'Insurance'),
  ('Sandton City Parking', NULL),
  ('Cell C', 'Utilities'),
  ('Electricity', 'Utilities'),
  ('Discovery', 'Health'),
  ('Github', 'Subscriptions'),
  ('Standard Bank', NULL),
  ('Vodacom', 'Utilities'),
  ('Crue', 'Health'),
  ('Claude', 'Subscriptions'),
  ('Bolt', 'Transport'),
  -- Groceries
  ('Pick n Pay', 'Groceries'),
  ('Shoprite', 'Groceries'),
  ('SPAR', 'Groceries'),
  ('Food Lovers Market', 'Groceries'),
  ('Boxer', 'Groceries'),
  ('Makro', 'Groceries'),
  -- Dining Out
  ('KFC', 'Dining Out'),
  ('Steers', 'Dining Out'),
  ('Debonairs', 'Dining Out'),
  ('Burger King', 'Dining Out'),
  ('Wimpy', 'Dining Out'),
  ('Spur', 'Dining Out'),
  ('Ocean Basket', 'Dining Out'),
  ('RocoMamas', 'Dining Out'),
  ('Chicken Licken', 'Dining Out'),
  ('Fishaways', 'Dining Out'),
  ('Panarottis', 'Dining Out'),
  ('Mugg and Bean', 'Dining Out'),
  ('Vida e Caffe', 'Dining Out'),
  ('Simply Asia', 'Dining Out'),
  ('Kauai', 'Dining Out'),
  ('Seattle Coffee', 'Dining Out'),
  ('Krispy Kreme', 'Dining Out'),
  ('Bootlegger', 'Dining Out'),
  ('Mr D Food', 'Dining Out'),
  -- Transport
  ('Shell', 'Transport'),
  ('Sasol', 'Transport'),
  ('Caltex', 'Transport'),
  ('Gautrain', 'Transport'),
  ('SANRAL', 'Transport'),
  ('Europcar', 'Transport'),
  ('inDrive', 'Transport'),
  -- Utilities
  ('MTN', 'Utilities'),
  ('Telkom', 'Utilities'),
  ('Afrihost', 'Utilities'),
  ('Webafrica', 'Utilities'),
  ('Vumatel', 'Utilities'),
  ('Openserve', 'Utilities'),
  ('Eskom', 'Utilities'),
  -- Health
  ('Medirite', 'Health'),
  ('Mediclinic', 'Health'),
  ('Netcare', 'Health'),
  ('Life Healthcare', 'Health'),
  ('Planet Fitness', 'Health'),
  ('Bodytec', 'Health'),
  -- Subscriptions
  ('Netflix', 'Subscriptions'),
  ('Showmax', 'Subscriptions'),
  ('DStv', 'Subscriptions'),
  ('YouTube', 'Subscriptions'),
  ('Microsoft', 'Subscriptions'),
  ('OpenAI', 'Subscriptions'),
  ('Adobe', 'Subscriptions'),
  ('PlayStation', 'Subscriptions'),
  ('Xbox', 'Subscriptions'),
  ('Amazon Prime', 'Subscriptions'),
  -- Education
  ('Udemy', 'Education'),
  ('Coursera', 'Education'),
  ('Duolingo', 'Education'),
  -- Shopping
  ('Superbalist', 'Shopping'),
  ('Mr Price', 'Shopping'),
  ('Ackermans', 'Shopping'),
  ('Truworths', 'Shopping'),
  ('Foschini', 'Shopping'),
  ('Edgars', 'Shopping'),
  ('Sportscene', 'Shopping'),
  ('Totalsports', 'Shopping'),
  ('Cape Union Mart', 'Shopping'),
  ('Cotton On', 'Shopping'),
  ('Builders Warehouse', 'Shopping'),
  ('Leroy Merlin', 'Shopping'),
  ('Incredible Connection', 'Shopping'),
  ('Sportsmans Warehouse', 'Shopping'),
  ('The Crazy Store', 'Shopping'),
  ('Bidorbuy', 'Shopping'),
  ('Temu', 'Shopping'),
  ('Shein', 'Shopping'),
  ('Exclusive Books', 'Shopping'),
  -- Entertainment
  ('Ster-Kinekor', 'Entertainment'),
  ('Nu Metro', 'Entertainment'),
  ('Computicket', 'Entertainment'),
  ('Webtickets', 'Entertainment'),
  -- Insurance
  ('OUTsurance', 'Insurance'),
  ('Santam', 'Insurance'),
  ('King Price', 'Insurance'),
  ('MiWay', 'Insurance'),
  ('Hollard', 'Insurance'),
  ('1Life', 'Insurance'),
  ('Budget Insurance', 'Insurance'),
  -- Savings
  ('EasyEquities', 'Savings'),
  ('Satrix', 'Savings'),
  ('Sygnia', 'Savings'),
  ('Coronation', 'Savings'),
  ('Ninety One', 'Savings'),
  ('Luno', 'Savings'),
  ('VALR', 'Savings'),
  ('Binance', 'Savings'),
  -- Bank charges are not a merchant, but description -> category is the same shape.
  ('Bank Fees', 'Fees')
ON CONFLICT (name) DO NOTHING;

INSERT INTO merchant_pattern (pattern, merchant_name) VALUES
  ('checkers', 'Checkers'),
  ('checkershyper', 'Checkers'),
  ('uber eats', 'Uber Eats'),
  ('new uber eats', 'Uber Eats'),
  ('uber', 'Uber'),
  ('apple.com', 'Apple'),
  ('apple', 'Apple'),
  ('capitec', 'Capitec'),
  ('allan gray', 'Allan Gray'),
  ('takealot', 'Takealot'),
  ('clicks', 'Clicks'),
  ('dischem', 'Dischem'),
  ('fnbcc', 'FNB'),
  ('fnb', 'FNB'),
  ('spotify', 'Spotify'),
  ('mcd', 'McDonalds'),
  ('mcdonald', 'McDonalds'),
  ('nandos', 'Nandos'),
  ('woolworths', 'Woolworths'),
  ('engen', 'Engen'),
  ('kumar kailey', 'Kumar Kailey'),
  ('virgin act', 'Virgin Active'),
  ('steamgames', 'Steam Games'),
  ('quicket', 'Quicket'),
  ('naked insurance', 'Naked Insurance'),
  ('sandton city parkin', 'Sandton City Parking'),
  ('cell c', 'Cell C'),
  ('cellc', 'Cell C'),
  ('electricity', 'Electricity'),
  ('DISC PREM', 'Discovery'),
  ('discovery', 'Discovery'),
  ('Github', 'Github'),
  ('standard bank', 'Standard Bank'),
  ('STANDARD', 'Standard Bank'),
  ('vodacom', 'Vodacom'),
  ('Crue', 'Crue'),
  ('Claude', 'Claude'),
  ('Claude.AI', 'Claude'),
  ('Bolt', 'Bolt'),
  -- Groceries
  ('pick n pay', 'Pick n Pay'),
  ('pick & pay', 'Pick n Pay'),
  ('picknpay', 'Pick n Pay'),
  ('shoprite', 'Shoprite'),
  -- Bare 'spar' is left out on purpose: it also matches SPARES and SPARTAN.
  ('superspar', 'SPAR'),
  ('kwikspar', 'SPAR'),
  ('sixty60', 'Checkers'),
  ('food lover', 'Food Lovers Market'),
  ('boxer', 'Boxer'),
  ('makro', 'Makro'),
  -- Dining Out
  ('kfc', 'KFC'),
  ('steers', 'Steers'),
  ('debonairs', 'Debonairs'),
  ('burger king', 'Burger King'),
  ('wimpy', 'Wimpy'),
  ('spur', 'Spur'),
  ('ocean basket', 'Ocean Basket'),
  ('rocomamas', 'RocoMamas'),
  ('chicken licken', 'Chicken Licken'),
  ('fishaways', 'Fishaways'),
  ('panarottis', 'Panarottis'),
  ('mugg', 'Mugg and Bean'),
  ('vida e caffe', 'Vida e Caffe'),
  ('simply asia', 'Simply Asia'),
  ('kauai', 'Kauai'),
  ('seattle coffee', 'Seattle Coffee'),
  ('krispy kreme', 'Krispy Kreme'),
  ('bootlegger', 'Bootlegger'),
  ('mr d food', 'Mr D Food'),
  -- Transport
  ('shell', 'Shell'),
  ('sasol', 'Sasol'),
  ('caltex', 'Caltex'),
  ('gautrain', 'Gautrain'),
  ('sanral', 'SANRAL'),
  ('europcar', 'Europcar'),
  ('indrive', 'inDrive'),
  -- Utilities
  ('mtn', 'MTN'),
  ('telkom', 'Telkom'),
  ('afrihost', 'Afrihost'),
  ('webafrica', 'Webafrica'),
  ('vumatel', 'Vumatel'),
  ('openserve', 'Openserve'),
  ('eskom', 'Eskom'),
  -- Health. The seeded 'dischem' pattern misses the hyphenated form the descriptor actually carries.
  ('dis-chem', 'Dischem'),
  ('dis chem', 'Dischem'),
  ('medirite', 'Medirite'),
  ('mediclinic', 'Mediclinic'),
  ('netcare', 'Netcare'),
  ('life healthcare', 'Life Healthcare'),
  ('planet fitness', 'Planet Fitness'),
  ('bodytec', 'Bodytec'),
  -- Subscriptions
  ('netflix', 'Netflix'),
  ('showmax', 'Showmax'),
  ('dstv', 'DStv'),
  ('multichoice', 'DStv'),
  ('youtube', 'YouTube'),
  ('microsoft', 'Microsoft'),
  ('openai', 'OpenAI'),
  ('adobe', 'Adobe'),
  ('playstation', 'PlayStation'),
  ('xbox', 'Xbox'),
  ('icloud', 'Apple'),
  ('amazon prime', 'Amazon Prime'),
  -- Education
  ('udemy', 'Udemy'),
  ('coursera', 'Coursera'),
  ('duolingo', 'Duolingo'),
  -- Shopping
  ('superbalist', 'Superbalist'),
  ('mr price', 'Mr Price'),
  ('ackermans', 'Ackermans'),
  ('truworths', 'Truworths'),
  ('foschini', 'Foschini'),
  ('edgars', 'Edgars'),
  ('sportscene', 'Sportscene'),
  ('totalsports', 'Totalsports'),
  ('cape union', 'Cape Union Mart'),
  ('cotton on', 'Cotton On'),
  ('builders', 'Builders Warehouse'),
  ('leroy merlin', 'Leroy Merlin'),
  ('incredible', 'Incredible Connection'),
  ('sportsmans', 'Sportsmans Warehouse'),
  ('crazy store', 'The Crazy Store'),
  ('bidorbuy', 'Bidorbuy'),
  ('temu', 'Temu'),
  ('shein', 'Shein'),
  ('exclusive books', 'Exclusive Books'),
  -- Entertainment
  ('ster-kinekor', 'Ster-Kinekor'),
  ('ster kinekor', 'Ster-Kinekor'),
  ('nu metro', 'Nu Metro'),
  ('computicket', 'Computicket'),
  ('webtickets', 'Webtickets'),
  -- Insurance
  ('outsurance', 'OUTsurance'),
  ('santam', 'Santam'),
  ('king price', 'King Price'),
  ('miway', 'MiWay'),
  ('hollard', 'Hollard'),
  ('1life', '1Life'),
  ('budget insurance', 'Budget Insurance'),
  -- Savings
  ('easyequities', 'EasyEquities'),
  ('satrix', 'Satrix'),
  ('sygnia', 'Sygnia'),
  ('coronation', 'Coronation'),
  ('ninety one', 'Ninety One'),
  ('luno', 'Luno'),
  ('valr', 'VALR'),
  ('binance', 'Binance'),
  -- Bank charges. 'standard bank fee' has to outrank the 'standard bank' merchant pattern, which is
  -- longer than 'bank fee' and would otherwise win the longest-first match.
  ('bank fee', 'Bank Fees'),
  ('st bank fee', 'Bank Fees'),
  ('standard bank fee', 'Bank Fees'),
  ('monthly account fee', 'Bank Fees'),
  ('service fee', 'Bank Fees')
ON CONFLICT (pattern) DO NOTHING;

-- The first version of this migration seeded Standard Bank as Income, verbatim from the old JSON.
-- The INSERT above cannot correct a database that has already run it, so fix it here.
UPDATE merchant
   SET default_category = NULL
 WHERE name = 'Standard Bank'
   AND default_category = 'Income';
